{% set name = "input4mips-validation" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}-meta

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/input4mips_validation-{{ version }}.tar.gz
    sha256: a9acc322b6fd78ccb72f845d79dc2e0c885f4620c096cf6622e3ec99b9ffb5e3

build:
  number: 0
requirements:
  host:
    - python

outputs:
  - name: {{ name|lower }}
    version: {{ version }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - input4mips-validation = input4mips_validation.cli:app

    requirements:
      host:
        - python >=3.9.0
        - poetry-core
      run:
        - python >=3.9.0
        - loguru >=0.7
        - cf_xarray >=0.8
        - xarray >=2022.0
        - pint-xarray >=0.3
        - numpy >=1.23, <2.0
        - cftime >=1.6
        - typing-extensions >=4.0
        - pooch >=1.0
        - netcdf4 >=1.0
        - attrs >=22.0
        - typer >=0.9.0
        - validators >=0.28.3
        - cattrs >=23.2.3
      run_constrained:
        - matplotlib-base >=3.0
        - notebook >=6.0

    test:
      imports:
        - input4mips_validation
      commands:
        - pip check
        - input4mips-validation --help
      requires:
        - pip

    about:
      home: https://input4mips-validation.readthedocs.io
      summary: Validation of input4MIPs data (checking file formats, metadata etc.).
      license: BSD-3-Clause
      license_file: LICENCE
      doc_url: https://input4mips-validation.readthedocs.io
      dev_url: https://github.com/climate-resource/input4mips_validation
      
  # A locked version, which will help avoid installation headaches
  # (e.g. dependency updates with breaking changes)
  # for those who just want the CLI.
  - name: {{ name|lower }}-locked
    version: {{ version }}
    build:
      skip: true  # [py != 39]
    requirements:
      host:
        - python
        - poetry-core

      run:
        - python
        - {{ pin_subpackage('input4mips-validation', exact=True) }}
        - {{ pin_compatible('attrs', min_pin='23.2.0', max_pin='23.2.1') }}
        - {{ pin_compatible('cattrs', min_pin='23.2.3', max_pin='23.2.4') }}
        - {{ pin_compatible('cftime', min_pin='1.6.4', max_pin='1.6.5') }}
        - {{ pin_compatible('cf_xarray', min_pin='0.9.3', max_pin='0.9.4') }}
        - {{ pin_compatible('loguru', min_pin='0.7.2', max_pin='0.7.3') }}
        - {{ pin_compatible('netcdf4', min_pin='1.7.1', max_pin='1.7.2') }}
        - {{ pin_compatible('numpy', min_pin='1.26.4', max_pin='1.26.5') }}
        - {{ pin_compatible('pint-xarray', min_pin='0.4.0', max_pin='0.4.1') }}
        - {{ pin_compatible('pooch', min_pin='1.8.2', max_pin='1.8.3') }}
        - {{ pin_compatible('typer', min_pin='0.12.3', max_pin='0.12.4') }}
        - {{ pin_compatible('typing-extensions', min_pin='4.12.2', max_pin='4.12.3') }}
        - {{ pin_compatible('validators', min_pin='0.33.0', max_pin='0.33.1') }}
        - {{ pin_compatible('xarray', min_pin='2024.6.0', max_pin='2024.6.1') }}
        
    test:
      imports:
        - input4mips_validation
      commands:
        - pip check
        - input4mips-validation --help
      requires:
        - pip
        
    about:
      home: https://input4mips-validation.readthedocs.io
      summary: Input4mips-validation with locked dependencies. Should help avoid breaks because of dependency updates.
      license: BSD-3-Clause
      license_file: LICENCE
      doc_url: https://input4mips-validation.readthedocs.io
      dev_url: https://github.com/climate-resource/input4mips_validation

about:
  home: https://input4mips-validation.readthedocs.io
  summary: Validation of input4MIPs data (checking file formats, metadata etc.).
  license: BSD-3-Clause
  license_file: LICENCE
  doc_url: https://input4mips-validation.readthedocs.io
  dev_url: https://github.com/climate-resource/input4mips_validation

extra:
  feedstock-name: input4mips-validation
  recipe-maintainers:
    - znichollscr
